name: ci

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [gcc_amd64_ci, clang_amd64_ci]
    steps:
      - id: checkout_repo
        uses: actions/checkout@v6

      - id: install_deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build \
            gcc g++ \
            clang clang-tidy clang-format \
            libcups2-dev cups-filters \
            python3-pip
          pip3 install cpplint

      - id: build_and_test
        run: cmake --workflow --preset ${{ matrix.preset }}

      - id: upload_artifacts
        if: failure() || success()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.preset }}
          path: build/${{ matrix.preset }}/
