name: Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build rpm
          pip install "cmake>=3.31"

      - name: Workflow
        run: cmake --workflow --preset default

      - name: Upload DEB
        uses: actions/upload-artifact@v7
        with:
          name: kyocera-drivers-${{ github.sha }}.deb
          path: build/default/*.deb
          if-no-files-found: error

      - name: Upload RPM
        uses: actions/upload-artifact@v7
        with:
          name: kyocera-drivers-${{ github.sha }}.rpm
          path: build/default/*.rpm
          if-no-files-found: error

      - name: Upload TGZ
        uses: actions/upload-artifact@v7
        with:
          name: kyocera-drivers-${{ github.sha }}.tgz
          path: build/default/*.tar.gz
          if-no-files-found: error
